version: '3.9'

services:
  server:
    image: seungchan1219/python-socket:server
    stdin_open: true
    tty: true
    deploy:
      mode: global

  cilent-seungchan:
    depends_on:
      - server
    image: seungchan1219/python-socket:client
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    command: /bin/ash -c "echo -e \"hi!\\n/wait\\nI'm Seungchan\\n/wait\" | python client_socket.py"

  cilent-minsu:
    depends_on:
      - server
    image: seungchan1219/python-socket:client
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    command: /bin/ash -c "echo -e \"/wait\\nhello!\\n/wait\\nI'm Minsu\" | python client_socket.py"