version: '3.9'

services:
  server:
    image: seungchan1219/python-socket:server
    stdin_open: true
    tty: true
    deploy:
      mode: global

  cilent:
    depends_on:
      - server
    image: seungchan1219/python-socket:client
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 2
